# Generated by Django 5.2.3 on 2025-06-20 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='building',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
