# Generated by Django 5.2.3 on 2025-07-07 05:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_city_country'),
    ]

    operations = [
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('travel_mode', models.CharField(choices=[('DRIVING', 'Driving'), ('WALKING', 'Walking'), ('BICYCLING', 'Bicycling'), ('TRANSIT', 'Transit')], max_length=10)),
                ('polyline', models.TextField()),
                ('distance_meters', models.FloatField()),
                ('duration_seconds', models.FloatField()),
                ('edge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='routes', to='api.edge')),
            ],
        ),
    ]
