# Generated by Django 5.2.3 on 2025-07-08 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_edge_is_default_edgealgorithm_edge_edge_algorithm'),
    ]

    operations = [
        migrations.AddField(
            model_name='edgealgorithm',
            name='parameters',
            field=models.JSONField(blank=True, help_text='Additional parameters for the algorithm', null=True),
        ),
    ]
