# Generated by Django 5.2.3 on 2025-07-09 14:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_edgealgorithm_total_edge_length'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='route',
            name='travel_mode',
        ),
        migrations.AlterField(
            model_name='route',
            name='edge',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='edge', to='api.edge'),
        ),
        migrations.CreateModel(
            name='EdgeTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('translation', models.CharField(choices=[('walking', 'Walking'), ('bicycling', 'Bicycling'), ('driving', 'Driving'), ('transit', 'Transit'), ('custom', 'Custom')], default='driving', max_length=32)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_default', models.BooleanField(default=False)),
                ('parameters', models.JSONField(blank=True, null=True)),
                ('total_edge_length', models.FloatField(blank=True, null=True)),
                ('edge', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.edge')),
            ],
        ),
        migrations.AddField(
            model_name='route',
            name='translation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='routes', to='api.edgetranslation'),
        ),
    ]
