# Generated by Django 5.2.3 on 2025-07-09 20:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_remove_route_travel_mode_alter_route_edge_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='edgetranslation',
            name='edge',
        ),
        migrations.AddField(
            model_name='edgetranslation',
            name='network',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.network'),
        ),
    ]
