# Generated by Django 5.2.3 on 2025-07-09 21:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_remove_edgetranslation_edge_edgetranslation_network'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='edgetranslation',
            name='network',
        ),
        migrations.AddField(
            model_name='edgetranslation',
            name='algorithm',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.edgealgorithm'),
        ),
    ]
