# Generated by Django 5.2.3 on 2025-07-24 02:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_remove_edgetranslation_network_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='route',
            name='sub_route',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='routes', to='api.route'),
        ),
    ]
