# Generated by Django 5.2.3 on 2025-07-24 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_route_sub_route'),
    ]

    operations = [
        migrations.AlterField(
            model_name='edgealgorithm',
            name='algorithm',
            field=models.CharField(choices=[('delaunay', 'Delaunay'), ('knn', 'KNN'), ('distance_threshold', 'Distance Threshold'), ('mst', 'Minimum Spanning Tree'), ('gabriel', 'Gabriel Graph'), ('beta_skeleton', 'Beta Skeleton'), ('rng', 'Relative Neighborhood Graph'), ('tsp', 'Traveling Salesman Problem'), ('custom', 'Custom')], default='delaunay', max_length=32),
        ),
    ]
