# Generated by Django 5.2.3 on 2025-08-14 18:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_alter_edgealgorithm_algorithm'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='junction',
            name='edge',
        ),
        migrations.RemoveField(
            model_name='pipe',
            name='edge',
        ),
        migrations.AddField(
            model_name='building',
            name='height',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='building',
            name='number_of_floors',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='node',
            name='boiler',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.boiler'),
        ),
        migrations.AddField(
            model_name='node',
            name='building',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.building'),
        ),
        migrations.AddField(
            model_name='node',
            name='geothermal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.geothermalsystem'),
        ),
        migrations.AddField(
            model_name='node',
            name='pv',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.pvsystem'),
        ),
        migrations.AddField(
            model_name='node',
            name='thermal_storage',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.thermalstorage'),
        ),
        migrations.AlterField(
            model_name='edgetranslation',
            name='translation',
            field=models.CharField(choices=[('walking', 'Walking'), ('transit', 'Transit'), ('custom', 'Custom')], default='transit', max_length=32),
        ),
        migrations.AlterField(
            model_name='node',
            name='node_type',
            field=models.CharField(choices=[('supply', 'Supply'), ('return', 'Return'), ('junction', 'Junction'), ('consumer', 'Consumer'), ('producer', 'Producer'), ('storage', 'Storage'), ('network', 'Network')], max_length=100),
        ),
        migrations.CreateModel(
            name='EnergyControllerCenter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('controller_type', models.CharField(choices=[('central', 'Central'), ('decentralized', 'Decentralized'), ('hybrid', 'Hybrid')], max_length=100)),
                ('model', models.CharField(max_length=100)),
                ('serial_number', models.CharField(max_length=100, unique=True)),
                ('installation_date', models.DateField()),
                ('last_maintenance', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('operational', 'Operational'), ('maintenance', 'Maintenance'), ('out_of_service', 'Out of Service')], default='operational', max_length=50)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('network', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.network')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.project')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='LoadProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_type', models.CharField(choices=[('heating', 'Heating'), ('cooling', 'Cooling'), ('electricity', 'Electricity'), ('water', 'Water'), ('gas', 'Gas')], max_length=100)),
                ('value', models.FloatField()),
                ('unit', models.CharField(choices=[('kW', 'kW')], max_length=20)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('boiler', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.boiler')),
                ('building', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.building')),
                ('geothermal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.geothermalsystem')),
                ('pv', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.pvsystem')),
                ('thermal_storage', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.thermalstorage')),
            ],
        ),
    ]
