# Generated by Django 5.2.3 on 2025-08-15 05:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_remove_junction_edge_remove_pipe_edge_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='node',
            name='branch_network',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='branch_nodes', to='api.network'),
        ),
    ]
