# Generated by Django 5.2.3 on 2025-08-15 07:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_node_branch_network'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='node',
            name='branch_network',
        ),
        migrations.AddField(
            model_name='network',
            name='parent_network',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.network'),
        ),
        migrations.AlterField(
            model_name='node',
            name='node_type',
            field=models.CharField(choices=[('supply', 'Supply'), ('return', 'Return'), ('junction', 'Junction'), ('consumer', 'Consumer'), ('producer', 'Producer'), ('storage', 'Storage')], max_length=100),
        ),
        migrations.CreateModel(
            name='Cluster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('type', models.CharField(choices=[('distance_based', 'Distance Based')], max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('network', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.network')),
            ],
        ),
    ]
