# Generated by Django 5.2.3 on 2025-08-16 15:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_remove_node_branch_network_network_parent_network_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='network',
            name='cluster',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='networks', to='api.cluster'),
        ),
        migrations.AlterField(
            model_name='cluster',
            name='network',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clusters', to='api.network'),
        ),
    ]
