# Generated by Django 5.2.3 on 2025-08-16 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_network_cluster_alter_cluster_network'),
    ]

    operations = [
        migrations.AddField(
            model_name='network',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='network',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
