# Generated by Django 5.2.3 on 2025-08-19 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_network_latitude_network_longitude'),
    ]

    operations = [
        migrations.AddField(
            model_name='route',
            name='route_type',
            field=models.CharField(choices=[('supply', 'Supply'), ('return', 'Return')], default='return', max_length=100),
        ),
        migrations.AlterField(
            model_name='node',
            name='node_type',
            field=models.CharField(choices=[('junction', 'Junction'), ('consumer', 'Consumer'), ('producer', 'Producer'), ('storage', 'Storage')], max_length=100),
        ),
    ]
